language: node_js
node_js:
  - iojs-v1.4.2
  - "0.12"
  - "0.11"
  - "0.10"
after_script: ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly ./spec/**/*_spec.js -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
